### ISSUE TITLE
Unmarshalling a GeoJSON from openstreetmap

### ISSUE THREAD

**Issue by mseshachalam** [twpayne/go-geom#133]
Hi, Thanks for the library. I'm new to dealing with geo related science. I am trying to use city boundary polygons from openstreetmap and do ops like find near by points and is point in a polygon. 

We can download the GeoJSON dump from this link.
http://polygons.openstreetmap.fr/index.py?id=1766358

```
var geometry geom.T
if err := geojson.Unmarshal(waypoint, &geometry); err != nil {
	return err
}
_, ok := geometry.(*geom.GeometryCollection)
```
I am not sure what to convert the geometry to. 

Could you please point me in the right direction ?

**Comment by twpayne** [comment]
@mseshachalam did you find a solution to your problem? If not, please re-open this issue.

**Comment by dechristopher** [comment]
@mseshachalam, my PR resolves your issue and allows for decoding bytes read in from GeoJSON files to an interface shading the underlying geo types using the new DecodeGeoJSON function. The library's implementation falls short when trying to type assert the geo.T type to the other geo types because they don't actually directly implement geo.T.
