### ISSUE TITLE
Polygon.Area() result does not match with geojson.io value

### ISSUE THREAD

**Issue by aneeskA** [twpayne/go-geom#139]
When using the following GeoJSON 
```json
{
    "type": "Polygon",
    "coordinates": [
        [
            [
                -105.58281422838608,
                41.33023341916364
            ],
            [
                -105.58281408553712,
                41.33042554378588
            ],
            [
                -105.58244996842966,
                41.33042600155808
            ],
            [
                -105.58245011344185,
                41.33023404891613
            ],
            [
                -105.58281422838608,
                41.33023341916364
            ]
        ]
    ]
}
```
at geojson.io, produces area as: 
```
Sq. Meters | 650.67
Sq. Kilometers | 0.00
Sq. Feet | 7003.76
Acres | 0.16
Sq. Miles | 0.00
```

When I modify `polygon_test.go` using the above coordinates:
```
func ExampleNewPolygon() {
	unitSquare := NewPolygon(XY).MustSetCoords([][]Coord{
		{
			{-105.58281422838608, 41.33023341916364},
			{-105.58281408553712, 41.33042554378588},
			{-105.58244996842966, 41.33042600155808},
			{-105.58245011344185, 41.33023404891613},
			{-105.58281422838608, 41.33023341916364}},
	})
	a := unitSquare.Area()
	fmt.Printf("unitSquare.Area() == %f", a)
	// Output: unitSquare.Area() == -0.0000000699242652662667
}
```

area calculated is `-0.0000000699242652662667`; not same as any of the numbers shown in GeoJSON.io. 

Questions
1. Why is the value different? 
2. What is the unit of area?
3. How can I set the unit?

**Comment by twpayne** [comment]
`go-geom` only does 2D (flat Cartesian) geometry.

The coordinates of your polygon are in latitude/longitude degrees. This means that the value returned from `Polygon.Area` is in "degrees squared" which is meaningless because the "size" of a degree depends on where you are on the surface of the earth.

If you want an area in "meters squared" or similar then you must first convert your degrees to meters, which is what map projections do.

Hope this helps!
