### ISSUE TITLE
Potential collision and risk from indirect dependence "github.com/gotestyourself/gotestyourself"

### ISSUE THREAD

**Issue by KateGo520** [twpayne/go-geom#182]
## Background
Repo `twpayne/go-geom` used the old path to import `gotestyourself` indirectly.
This caused that `github.com/gotestyourself/gotestyourself` and `gotest.tools` coexist in this repo：
https://github.com/twpayne/go-geom/blob/master/go.mod （Line 13 & 21）
```
github.com/gotestyourself/gotestyourself v2.2.0+incompatible // indirect
gotest.tools v2.2.0+incompatible // indirect 
```

That’s because the `gotestyourself` has already renamed it’s import path from "github.com/gotestyourself/gotestyourself" to "gotest.tools". When you use the old path "github.com/gotestyourself/gotestyourself" to import the `gotestyourself`, will reintroduces `gotestyourself` through the import statements "import gotest.tools" in the go source file of `gotestyourself`.

https://github.com/gotestyourself/gotest.tools/blob/v2.2.0/fs/example_test.go#L8 
```
package fs_test
import (
	…
	"gotest.tools/assert"
	"gotest.tools/assert/cmp"
	"gotest.tools/fs"
	"gotest.tools/golden"
)
```

"github.com/gotestyourself/gotestyourself" and "gotest.tools" are the same repos. This will work in isolation, bring about potential risks and problems. 

## Solution
Add replace statement in the go.mod file:
```
replace github.com/gotestyourself/gotestyourself => gotest.tools v2.3.0
```
Then clean the go.mod.

**Comment by KateGo520** [comment]
@twpayne  Could you help me review this issue? Thx :p

**Comment by twpayne** [comment]
Thanks for reporting this.

`github.com/gotestyourself/gotestyourself` is brought in by a dependency of `go-geom` that is only used in tests, namely `github.com/ory/dockertest`. There is no potential collision because tests are compiled into separate binaries run independently, and the test code is not included in the final library code.

Rather than using a `replace` directive in `go.mod`, the correct fix is to update the test dependency to a more recent version that depends on `gotest.tools` instead of `gotestyourself`. This is done in commit ac99c5a66224c8ac0b37c09a376ba37de8fb70be.

Thanks again for reporting!

**Comment by twpayne** [comment]
I've tagged `v1.3.4` that includes this fix.
