### ISSUE TITLE
incorrect handling of GEOMETRYCOLLECTION Z/M/ZM EMPTY

### ISSUE THREAD

**Issue by otan** [twpayne/go-geom#189]
At time of writing, GEOMETRYCOLLECTION handles layout by scanning through every item in the GEOMETRYCOLLECTION and finding the max layout.

For empty GEOMETRYCOLLECTION, `Layout()` would return `NoLayout`. This makes it impossible to differentiate between `GEOMETRYCOLLECTION`, `GEOMETRYCOLLECTION Z`, `GEOMETRYCOLLECTION M` and `GEOMETRYCOLLECTION ZM`.

There are a few solutions I can think of. This simplest would be to introduce a `emptyLayout` on `GeometryCollection`. The interface would be `geom.NewGeometryCollectionEmpty(layout)`.

However, in PostGIS at least, GeometryCollections cannot have mixed dimensions. If that's something we also want to enforce, we really should be changing `NewGeometryCollection` to take in a layout argument and `Push`/`MustPush` only accepts the geometry if it is the same dimension, i.e. `geom.NewGeometryCollection(geom.XY)`. This is an API change though so I expect this would be a major version bump.

We could have some sort of hybrid thing, where a layout argument to `NewGeometryCollection` is optional, where being not specified by default means it is NoLayout. Adding the first geometry would change the dimensionality accordingly (if it is NoLayout). Open question as to whether we support mixed-dimensions in this case though -- if not, this will not affect the API on upgrade and seems like a happy intermediate solution. 

cc @twpayne for your thoughts.

**Comment by twpayne** [comment]
Nice catch, thank you!

Ah, GeometryCollections... the under-specified geometry type that is completely different to every other geometry type and yet still must be treated as a geometry type. How I've missed you 🙄 

The [OGC spec](https://portal.ogc.org/files/?artifact_id=25355) explicitly allows mixed layouts in GeometryCollections (section 6.1.3.1):

> A GeometryCollection is a geometric object that is a collection of some number of geometric objects.
> All the elements in a GeometryCollection shall be in the same Spatial Reference System. This is also the Spatial
Reference System for the GeometryCollection.
> GeometryCollection places no other constraints on its elements. Subclasses of GeometryCollection may restrict
membership based on dimension and may also place other constraints on the degree of spatial overlap between
elements.

That said, PostGIS, by being be far the most widely used implementation, effectively defines the standard here.

My initial thought is that I think we can support all the functionality needed here without breaking API compatibility. Specifically:

1. We add an explicit `layout` field to `GeometryCollection`, which is by default `NoLayout` (the zero value).
2. We add a new method `GeometryCollection.SetLayout(Layout)` to allow the user to change this to, say, `geom.XY`.
3. We modify the behavior of `Push` and `MustPush` to accept any layout if the `GeometryCollection`'s layout is `NoLayout`, otherwise they enforce that the added geometry's layout must match the `GeometryCollections`.
4. We modify `GeometryCollection.Layout` to preserve the existing behavior (scan for the most specific layout that covers all geometries in the collection) if its layout is `NoLayout`, otherwise it simply returns the `GeometryCollection`'s layout.
5. For correctness, `GeometryCollection.SetLayout(Layout)` must check that all the geometries in the collection have the desired layout, and return an error otherwise.
6. I would also add a `GeometryCollection.MustSetLayout(Layout)` function that calls `SetLayout`, panics on any error, and returns the `GeometryCollection`.

With this you can do things like:
```go
mixedGeomCollection := geom.NewGeometryCollection()
zmGeomCollection := geom.NewGeometryCollection().MustSetLayout(geom.ZM)
err := zmGeomCollection.Push(geom.NewPointEmpty(geom.XYZM)) // succeeds
err := zmGeomCollection.Push(geom.NewPointEmpty(geom.XY)) // returns an error
```

The advantage of this approach is that it enables the mixed-layout behavior while also allowing us to constrain the layout of a geometry collection, without breaking backwards compatibility. I think that having an explicit `SetLayout` call is better than using the layout of the first geometry added as it preserves flexibility and allows empty geometry collections to have a layout.

Note also that I'm very happy to bump major versions if we settle on a solution that breaks backwards compatibility - this is exactly why we have versioning :)

**Comment by twpayne** [comment]
I think that with #190 merged we can close this as fixed. Thank you both @otan and @andyyang890 :) Please re-open if needed.
